### ISSUE TITLE
好像没有办法支持 CocoaPods 升级啊

### ISSUE THREAD

**Issue by aUcidme** [bmob/Bmob-iOS-SDK#6]
在 Podfile 里添加了如下设置
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'CompetitionProject' do
pod 'BmobSDK'
end

但是只能下载到 2.1.7，没办法直接下载安装 2.1.8

**Comment by Coder-LiuZW** [comment]
目前最新版本是v2.1.9，请更新本地仓库使用。
