### ISSUE TITLE
支持ipv6吗？

### ISSUE THREAD

**Issue by LiuSky** [bmob/Bmob-iOS-SDK#9]
我今天早上审核被拒绝了。说是在10.3.2的系统上面连接不上网络。说是ipv6问题。请回复下。谢谢。
@Coder-LiuZW

**Comment by JoyHong** [comment]
解决了吗？
我也被拒了N多次了。

**Comment by LiuSky** [comment]
这个问题貌似不实bmob的sdk 问题。苹果那边审核有时候就是会发神经吧说不行。你可以尝试下你这边用vip6上面。

**Comment by JoyHong** [comment]
肯定要按照苹果的来的。。
我们公司的服务器就一次性通过了。
不知道为什么bmob的服务器会这个样子。
